# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Exercism
    init: sudo bash ./scripts/init-gitpod.sh
    command: sudo cp -a ./exercism /usr/local/bin
  - name: Install node packages
    init: npm install
  - name: Build containers
    init: docker-compose up --remove-orphans

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
