# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Init Exercism CLI
    init: bash ./scripts/install-exercism.sh
    command: ./exercism configure --token=${EXERCISM_TOKEN}
  - name: Install node packages
    init: npm install
  - name: Build containers
    init: docker-compose up --remove-orphans

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
