version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php74-cli.dockerfile
    volumes:
      - ./:/source
    working_dir: /source
    tty: true
  composer:
    image: composer
    volumes:
      - ./:/app
    command:
      - composer
      - update
